### PR TITLE
Many updates to get CRAN-ready and add a few features

### PR DESCRIPTION
**Pull request by hafen**
This started out as a few small tweaks but ended up a bit larger than that. A summary of what has been done is provided here: https://github.com/hafen/osfr/blob/master/NEWS.md. Sorry to PR out of the blue but we've been using this updated package as a team and its use may grow larger so it would be great to see if the changes are something that can be merged back into the main repository.

### CODE REVIEW

**Comment by chartgerink** [comment]
Thanks! I'll go through this within the next week, but it looks like you picked up several aspects that were remnants from old, shaping versions.

**Comment by hafen** [comment]
Thanks! Let me know if you have any questions. I took a few liberties to make the CRAN check happy (such as the choice of license) that are of course completely up to you to do what you would like with.

**Comment by hafen** [comment]
The Travis CI check fails because it depends on an environment variable `OSF_PAT_TEST` to be set in https://travis-ci.org/chartgerink/osfr/settings.

**Comment by hafen** [comment]
Also, I wanted to note that this is a great project that seems like it might fit in very well in the ROpenSci (https://ropensci.org/) community and am curious what your thoughts are on that (ping @jeffspies and @karthik for thoughts as well).

**Comment by chartgerink** [comment]
Thanks @hafen, I'll try and get the Travis build corrected. I always choose CC 0, but didn't know about the liability aspect. I'll consider MIT but am leaning towards GPLv3. Could you maybe elaborate why you chose MIT over GPLv3 if that was a conscious choice?

Funny thing: I initially started this project due to a tweet by @karthik but have been very tardy on this for which he might dislike me by now (it's been two years). I'm finishing up a few projects and with your PR I have some incentive to get going again (I hope 😊 ).

**Comment by hafen** [comment]
Great! Thanks! I still think this would be a great rOpenSci project - good to hear you already have been in touch with @karthik about it. I'm sure he doesn't dislike you 😀. I hope you don't mind I opened an issue on ROpenSci (https://github.com/ropensci/wishlist/issues/30) mentioning this package.

**Pull request merged**
